ALTER TABLE "Products" DROP CONSTRAINT IF EXISTS "Products_fk0";

ALTER TABLE "Products" DROP CONSTRAINT IF EXISTS "Products_fk1";

ALTER TABLE "Products" DROP CONSTRAINT IF EXISTS "Products_fk2";

ALTER TABLE "Orders" DROP CONSTRAINT IF EXISTS "Orders_fk0";

ALTER TABLE "LineItems" DROP CONSTRAINT IF EXISTS "LineItems_fk0";

ALTER TABLE "LineItems" DROP CONSTRAINT IF EXISTS "LineItems_fk1";

DROP TABLE IF EXISTS "Products";

DROP TABLE IF EXISTS "Categories";

DROP TABLE IF EXISTS "Currencies";

DROP TABLE IF EXISTS "Suppliers";

DROP TABLE IF EXISTS "Users";

DROP TABLE IF EXISTS "Orders";

DROP TABLE IF EXISTS "LineItems";

